### PR TITLE
blogging.rst: Add section for blogging

### LINKED ISSUE #3: Mention Blogging
Points to include:

- How to ask for invite for https://blogs.amuoss.tk?
- Always register your email so that in case you forget your password, you don't get locked out of your account.
- How to make blog public?
- How to subscribe your RSS feed in the #blog-students channel?

### PR DESCRIPTION
**Pull request by roshnet**
Fixes #3

### CODE REVIEW

**Comment by RJ722** [comment]
This is very well written!

Thanks @roshnet! :-)

Just one more thing, can you rebase your branch with `upstream/master` once, please?

I'm not sure what is happening here - but when I checkout the [roshnet/add-section-blogging](https://github.com/roshnet/whattodo/tree/add-section-blogging) locally and then do `git diff master` (master is synced to latest `upstream/master`, I get this:

```diff
-Recommended Reading
+Reading Material
--------------------
+----------------

-"Must read" articles for anyone who is doing anything even remotely related to
-technology:
-
-- `"How To Ask Questions The Smart Way" by Eric Steven Raymond <http://catb.org/~esr/faqs/smart-questions.html>`_.
+- `"How To Ask Questions The Smart Way" by Eric Steven Raymond <http://catb.org/~esr/faqs/smart-questions.html>`_
 - `"Getting Answers" by Mike Ash <https://www.mikeash.com/getting_answers.html>`_.
 - `"Teach Yourself Programming in Ten Years" by Peter Norvig <http://norvig.com/21-days.html>`_.
-- `"Why I wrote PGP" by Philip Zimmermann <https://www.philzimmermann.com/EN/essays/WhyIWrotePGP.html>`_.
```

This is basically reverting the changes I did in https://github.com/amu-oss/whattodo/commit/9a36d6e4e2adc30f50021b77b58923afa3b5cb22. And somehow (intelligently or dumbly), GitHub isn't showing these changes in the "Files Changed" section of this PR.

Any ideas why?

**Comment by roshnet** [comment]
Ah okay, let me have a look at the possible cause.

**Comment by RJ722** [comment]
@roshnet can you run the following commands one (for the sake of rebasing)?

```
git checkout add-section-blogging
git fetch upstream
git rebase upstream/master
git push origin add-section-blogging
```

**Comment by RJ722** [comment]
Nevermind, I did the rebase myself, but it had a side-effect that the commit ID's changed and now GitHub won't shows this PR as merged.

Rest assured that the commits (598c4eae98474a38de683e4f3c57bfaeb3a65786 8028460bc3b4dbb4a3f7f09c185c091b1bf5b2cf 08ec23828382de8b15b0116862e35782c639ef57) have you as author! :-)

Thanks!

**Pull request closed without merging**
